config/routes.rb
Rails.application.routes.draw do
root 'pages#index'
# CRUD - Create Read Update Delete
resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 #this is responsible for showing all pages
  def index
    #local var only available in local method
    # if we want our view to have access to the var
    # we need an instance variable
    @pages = Page.all
    # render :index
  end

  #responsible for showing a specific page
  def show
    
    @page = Page.find(params[:id])
    #render :show - app/views/pages/show.html.erb
  end

  #responsible for showing a form to edit an existing page
  def edit
    @page = Page.find(params[:id])
    #render :edit - app/views/pages/edit.html.erb
  end

  #responsible for updating the values of pre-existing record
  def update
    @page = Page.find(params[:id])
      if @page.update(page_params)
        redirect_to page_path(@page)
      else
        render :edit
      end
  end

  #responsible for showing a form to create a new page
  def new
    @page = Page.new
    #render :new - app/views/pages/new.html.erb
  end

  #respnsible for saving a new record in our database
  def create
    #strong params
    page = Page.create(page_params)
    if page.save
      redirect_to page_path(page)
    else
      render :new
    end
  end

  def destroy
    page = Page.find(params[:id])
    page.destroy
    redirect_to pages_path
  end

  private
    def page_params
      params.require(:page).permit(:title, :author, :body, :private)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1> Editing: <%= @page.title %> </h1>

<%= form_for @page do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Title', required: true %>
  </div>

  <div>
    <%= f.label :author %>
    <%= f.text_field :author, placeholder: 'Author', required: true %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: 'Body', required: true %>
  </div>

  <div>
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>

  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>All Blog Posts</h1>
<%= link_to 'New Blog Post', new_page_path %>
<hr />
<% @pages.each do |page| %>
  <div>
    <h3>
      <%= link_to page.title, page_path(page) %>
    </h3>
    <i>Author: <%= page.author %></i>
    
    <strong>PRIVATE: <%= page.private ? 'Yes' : 'No' %></strong>
    <%= link_to 'Delete', page_path(page), method: :delete %>
  </div>
  <hr />
<% end %>
<!-- NON ECHOING ERB TAG -->
<!-- loops, conditionals, variables -->
<% %>

<!-- ECHOING ERB TAG -->
<!-- print out the value of a variable -->
<%= %>

app/views/pages/new.html.erb
<h1>Create New Blog Post</h1>

<%= form_for @page do |f| %>
  <div>  
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Title', required: true %>
  </div>

  <div>
    <%= f.label :author %>
    <%= f.text_field :author, placeholder: 'Author', required: true  %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: 'Body', required: true  %>
  </div>

  <div>
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>

  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1>
<%= @page.title %>
</h1>

<i>Author: <%= @page.author %> </i>
<br />
<i>Created: <%= @page.created_at %> </i>

<hr />
<p>
<%= @page.body %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Back', pages_path %>